name: Add Label

on:
  pull_request:
    types: opened
  
  issues:
    types: opened
  

jobs:
  add_label:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: mylabel
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
permissions:
  contents: read
  issues: write
  pull-requests: write
