name: Add Label

on:
  pull_request:
    types: opened
  
  issues:
    types: opened
  

jobs:
  add_label:
    permissions:
     actions: write
     checks: write
     contents: write
     deployments: write
     discussions: write
     issues: write
     pull-requests: write
     packages: write
     repository-projects: write
     security-events: write
     statuses: write
     id-token: write
     pages: write
     
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: mylabel
